# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Software Architect's Handbook
description: >-
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

baseurl: /handbook/
url: https://martyn82.github.io
github_username:  martyn82
#paginate:         5
repository:       martyn82/handbook

github:
  repo: https://github.com/martyn82/handbook

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site-wide data

quality:
  Compatibility: Degree to which a product, system or component can exchange information with other products, systems or components, and/or perform its required functions, while sharing the same hardware or software environment.
  'Functional suitability': This characteristic represents the degree to which a product or system provides functions that meet stated and implied needs when used under specified conditions.
  Maintainability: This characteristic represents the degree of effectiveness and efficiency with which a product or system can be modified to improve it, correct it or adapt it to changes in environment, and in requirements.
  'Performance efficiency': This characteristic represents the performance relative to the amount of resources used under stated conditions.
  Portability: Degree of effectiveness and efficiency with which a system, product or component can be transferred from one hardware, software or other operational or usage environment to another.
  Reliability: Degree to which a system, product or component performs specified functions under specified conditions for a specified period of time.
  Security: Degree to which a product or system protects information and data so that persons or other products or systems have the degree of data access appropriate to their types and levels of authorisation.
  Usability: Degree to which a product or system can be used by specified users to achieve specified goals with effectiveness, efficiency and satisfaction in a specified context of use.

qualities:
  Compatibility:
    'Co-existence': Degree to which a product can perform its required functions efficiently while sharing a common environment and resources with other products, without detrimental impact on any other product.
    Interoperability: Degree to which two or more systems, products or components can exchange information and use the information that has been exchanged.
  'Functional suitability':
    'Functional completeness': Degree to which the set of functions covers all the specified tasks and user objectives.
    'Functional correctness': Degree to which a product or system provides the correct results with the needed degree of precision.
    'Functional appropriateness': Degree to which the functions facilitate the accomplishment of specified tasks and objectives.
  Maintainability:
    Modularity: Degree to which a system or computer program is composed of discrete components such that a change to one component has minimal impact on other components.
    Reusability: Degree to which an asset can be used in more than one system, or in building other assets.
    Analysability: Degree of effectiveness and efficiency with which it is possible to assess the impact on a product or system of an intended change to one or more of its parts, or to diagnose a product for deficiencies or causes of failures, or to identify parts to be modified.
    Modifiability: Degree to which a product or system can be effectively and efficiently modified without introducing defects or degrading existing product quality.
    Testability: Degree of effectiveness and efficiency with which test criteria can be established for a system, product or component and tests can be performed to determine whether those criteria have been met.
  'Performance efficiency':
    'Time behaviour': >-
      Degree to which the response and processing times and throughput rates of a product or system, when performing
      its functions, meet requirements.
    'Resource utilisation': >-
      Degree to which the amounts and types of resources used by a product or system, when performing its functions,
      meet requirements.
    Capacity: Degree to which the maximum limits of a product or system parameter meet requirements.
  Portability:
    Adaptability: >-
      Degree to which a product or system can effectively and efficiently be adapted for different or evolving
      hardware, software or other operational or usage environments.
    Installability: >-
      Degree of effectiveness and efficiency with which a product or system can be successfully installed and/or
      uninstalled in a specified environment.
    Replaceability: >-
      Degree to which a product can replace another specified software product for the same purpose in the same
      environment.
  Reliability:
    Maturity: Degree to which a system, product or component meets needs for reliability under normal operation.
    Availability: Degree to which a system, product or component is operational and accessible when required for use.
    'Fault tolerance': Degree to which a system, product or component operates as intended despite the presence of hardware or software faults.
    Recoverability: Degree to which, in the event of an interruption or a failure, a product or system can recover the data directly affected and re-establish the desired state of the system.
  Security:
    Confidentiality: Degree to which a product or system ensures that data are accessible only to those authorised to have access.
    Integrity: Degree to which a system, product or component prevents unauthorised access to, or modification of, computer programs or data.
    Non-repudiation: Degree to which actions or events can be proven to have taken place, so that the events or actions cannot be repudiated later.
    Accountability: Degree to which the actions of an entity can be traced uniquely to the entity.
    Authenticity: Degree to which the identity of a subject or resource can be proved to be the one claimed.
  Usability:
    'Appropriateness recognisability': Degree to which users can recognize whether a product or system is appropriate for their needs.
    Learnability: >-
      Degree to which a product or system can be used by specified users to achieve specified goals of learning to
      use the product or system with effectiveness, efficiency, freedom from risk and satisfaction in a specified context
      of use.
    Operability: Degree to which a product or system has attributes that make it easy to operate and control.
    'User-error protection': Degree to which a system protects users against making errors.
    'User interface aesthetics': Degree to which a user interface enables pleasing and satisfying interaction for the user.
    Accessibility: >-
      Degree to which a product or system can be used by people with the widest range of characteristics and
      capabilities to achieve a specified goal in a specified context of use.
